### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wbhef** [MikasaLee/DDPTransformer#1]
Note: you should install v2 branch.Could you please provide a detailed explanation of this sentence? I would be extremely grateful

**Comment by MikasaLee** [comment]
![图片](https://github.com/user-attachments/assets/b86db962-b5d8-4293-adf8-654cd838bde7)
Thanks for your issue!
Our code depend on the [torch-radon](https://github.com/matteo-ronchetti/torch-radon) library,as shown in picture,the torch-radon have two branch(master and v2)，and the master branch is default. But our code depend on v2 branch。so you should install v2 branch。
